version: "2"

networks:
  internal:
    driver: bridge
services:
  apache:
    container_name: "prod_front_intellect"
    image: "webdevops/apache"
    volumes:
      - "../frontend/dist/spa:/app"
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontintellect.rule=Host(`frontintellect.alvitre.com.br`,`www.frontintellect.alvitre.com.br`)"
      - "traefik.http.services.frontintellect.loadbalancer.server.port=80"

  backend:
    container_name: "prod_api_intellect"
    image: "node:lts-alpine"
    working_dir: /app
    volumes:
      - "../backend:/app"
    networks:
      - internal
    command: "npm run prod"
    ports:
      - 4444:4333
      - 9229:9229
      - 7001:7001
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.backintellect.rule=Host(`backintellect.alvitre.com.br`)
      - traefik.http.services.backintellect.loadbalancer.server.port=4333
