version: "2"

networks:
  internal:
    driver: bridge

services:
  goback:
    container_name: "goback"
    image: golang:1.15.7
    volumes:
      # - ../backgo/bin:/app
      - ../backgo:/app
      - "/home/alvitre/go:/go"
    networks:
      - internal
    # command: "/bin/sh -c 'cd /app && ls && ./server'" 
    command: "/bin/sh -c 'cd /app && reflex -c /app/reflex.conf'" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.golang.rule=Host(`golang.localhost`)"
      - "traefik.http.services.golang.loadbalancer.server.port=4000"
        
  # backend:
  #   container_name: "api_intellect"
  #   image: "node:lts-alpine"
  #   working_dir: /app
  #   volumes:
  #     - "../backend:/app"
  #   networks:
  #     - internal
  #   command: "npm run ts"
  #   ports:
  #     - 4444:4333
  #     - 9229:9229
  #     - 7001:7001
  #   labels:
  #     - "traefik.enable=true"
  #     - traefik.http.routers.backintellect.rule=Host(`backintellect.localhost`)
  #     - traefik.http.services.backintellect.loadbalancer.server.port=4333

  frontend:
    container_name: "frontend_intellect"
    image: "node:lts-alpine"
    working_dir: /app
    volumes:
      - "../frontend:/app"
    command: "yarn run dev"
    ports:
      - 2083:2083
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.frontintellect.rule=Host(`frontintellect.localhost`)
      - traefik.http.services.frontintellect.loadbalancer.server.port=2083
