version: "3"

networks:
  internal:
    driver: bridge

services:
  backend:
    container_name: "api_intellect"
    image: "node:lts-alpine"
    working_dir: /app
    volumes:
      - "../backend:/app"
    networks:
      - internal
    command: "npm run ts"
    ports:
      - 4444:4333
      - 9229:9229
      - 7001:7001
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.backintellect.rule=Host(`backintellect.${DOMAIN}`)
      - traefik.http.services.backintellect.loadbalancer.server.port=4333

  frontend:
    container_name: "frontend"
    image: "node:lts-alpine"
    environment:
      - HOST=frontend.${DOMAIN}
    working_dir: /app
    volumes:
      - "../frontend:/app"
    command: "npm run dev"
    ports:
      - 8000:8000
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.frontintellect.rule=Host(`frontintellect.${DOMAIN}`)
      - traefik.http.services.frontintellect.loadbalancer.server.port=8000

  # mysqlintellect:
  #   container_name: ${HOST}
  #   build:
  #     context: ../database
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_DATABASE: intellect
  #     MYSQL_USER: intellect
  #     MYSQL_ROOT_PASSWORD: intellect
  #     MYSQL_PASSWORD: intellect
  #     SERVICE_NAME: ${HOST}
  #   volumes:
  #     - ../database/mysql:/var/lib/mysql
  #   networks:
  #     - intellect

  # phpmyadmin_intellect:
  #   container_name: "phpmyadmin_intellect"
  #   image: phpmyadmin/phpmyadmin:latest
  #   environment:
  #     PMA_HOST: mysqlintellect
  #   depends_on:
  #     - mysqlintellect
  #   ports:
  #     - 2050:80
  #   networks:
  #     - intellect
  #   labels:
  #     - "traefik.enable=true"
  #     - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${DOMAIN}`)
  #     - traefik.http.services.phpmyadmin.loadbalancer.server.port=80

  # traefik_acolher:
  #   image: "traefik"
  #   command:
  #     - "--api.insecure=true"
  #     - "--api.dashboard=true"
  #     - "--api.debug=true"
  #     - "--providers.docker"
  #     - "--providers.docker.exposedByDefault=false"
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.websecure.address=:443"
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - intellect
