version: "2"
services:
  nginx_acolher:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`acolher.localhost`)"

  traefik_acolher:
    image: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - acolher
