version: "2"

networks:
  intellect:
    driver: bridge

services:
  api_intellect:
    container_name: "api_intellect"
    build:
      context: "../../node"
    environment:
      PMA_HOST: mysqlintellect
    volumes:
      - "../../node:/app"
    networks:
      - intellect
    depends_on:
      - mysqlintellect
    ports:
      - "4333:4333"

  quasar:
    container_name: "quasar"
    build:
      context: "../../quasar"
    environment:
      - HOST=0.0.0.0
    working_dir: /app
    volumes:
      - "../../quasar:/app"
    networks:
      - intellect
    ports:
      - "8080:8080"

  mysqlintellect:
    container_name: mysqlintellect
    build:
      context: ../../database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: intellect
      MYSQL_USER: intellect
      MYSQL_ROOT_PASSWORD: intellect
      MYSQL_PASSWORD: intellect
      SERVICE_NAME: mysql
    volumes:
      - ../../database/mysql:/var/lib/mysql
    networks:
      - intellect

  phpmyadmin_intellect:
    container_name: "phpmyadmin_intellect"
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysqlintellect
    depends_on:
      - mysqlintellect
    ports:
      - 2050:80
    networks:
      - intellect
